---
- hosts: worker3  # Update this to match the host or group in your Ansible inventory
  become: yes

  tasks:
    - name: Copy JAR to remote server
      copy:
        src: /var/lib/jenkins/workspace/Hello-app-jar-ansible-deploy/target/hello-app.jar
        dest: /home/vagrant/hello-app.jar

    - name: Deploy JAR using java -jar command
      command: java -jar /home/vagrant/hello-app.jar &
