---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  type: NodePort
  selector:
    app: hello-app
  ports:
  - protocol: TCP
    port: 6701
    targetPort: 6701
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: helloapp
        image: narendra8686/hello-app-img:latest
        ports:
        - containerPort: 6701